### ISSUE TITLE
ImportError: DLL load failed while importing libtriton: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by muhammad-fiaz** [woct0rdho/triton-windows#38]
Hello @woct0rdho 

i have encountered this problem 
 ``` bash
 from triton._C.libtriton import ir, passes, llvm, amd
ImportError: DLL load failed while importing libtriton: A dynamic link library (DLL) initialization routine failed.
```

I using Python version 3.12.8 with `poetry` in `.venv`

`pyproject.toml`
```toml
[tool.poetry]
name = "projectname"
version = "0.0.0"
description = ""
authors = [""]
license = ""
readme = "README.md"

package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
logly = ">=0.0.6,<0.1.0"
packaging = ">=24.0,<25.0"
pandas = "^2.2"
numpy = "^1.26"
torch = [
    {platform="darwin", version = "2.5.1"},
    {platform="win64",url = "https://download.pytorch.org/whl/cu124/torch-2.5.1%2Bcu124-cp312-cp312-win_amd64.whl"}]
torchaudio =[
    {platform="darwin", version = "2.5.1"},
    {platform="win64",url = "https://download.pytorch.org/whl/cu124/torchaudio-2.5.1%2Bcu124-cp312-cp312-win_amd64.whl"}]
torchvision =[
    {platform="darwin", version = "0.20.1"},
    {platform="win64",url = "https://download.pytorch.org/whl/cu124/torchvision-0.20.1%2Bcu124-cp312-cp312-win_amd64.whl"}]
requests = "^2.32"
tqdm = "^4.67"
regex = "^2024.11"
sentencepiece = "^0.2"
tiktoken = "^0.8"
blobfile = "^3.0"
safetensors = "^0.5"
huggingface-hub = "^0.27"
triton =[
    {platform="win64", url = "https://github.com/woct0rdho/triton-windows/releases/download/v3.1.0-windows.post5/triton-3.1.0-cp312-cp312-win_amd64.whl"}
]
xformers = [
    {platform = "win64", url = "https://download.pytorch.org/whl/cu124/xformers-0.0.29.post1-cp312-cp312-win_amd64.whl"}
]
gradio = "^5.12"
transformers = "^4.48"
datasets = "^3.2"
trl = "^0.13"
peft = "^0.14"
bitsandbytes = "^0.45"

unsloth-zoo = "^2025.1.3"

unsloth = {extras = ["cu124-torch250", "huggingface"], version = "*"}

accelerate = "^1.2.1"
gradio-client = "^1.5.4"

[tool.poetry.group.dev.dependencies]
jupyter = "^1.1.1"
ipykernel = "^6.29.5"
poetry-plugin-export = "^1.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

```
I also tried this method

 If you see ImportError: DLL load failed, and there are vcruntime140.dll and vcruntime140_1.dll in the folder containing python.exe, then you may try:

- Install the latest version of vcredist from https://aka.ms/vs/17/release/vc_redist.x64.exe
- Copy-paste `msvcp140.dll`, `vcruntime140.dll`, and `vcruntime140_1.dll` from C:\Windows\System32\ to the folder containing python.exe, and replace the existing DLLs
- Delete the cache folders:
        C:\Users\<your username>\.triton\cache\
        C:\Users\<your username>\AppData\Local\Temp\torchinductor_<your username>\
You may also need to delete the cache folders when you change the Python version, install another version of Triton, or change the version of MSVC, Windows SDK, or CUDA.

for this above method I have pasted the `.dll` files inside the python installed folder where it has `python.exe` 

but it still shows this error but at first it worked but after changing `.venv` it does not work I tried clearing all caches and I even tried reinstalling Python and also tried without poetry using virtual env, but it does not work :)

if any solution works for you pls suggest me :)

I already have discussed this here [#13](https://github.com/woct0rdho/triton-windows/issues/13#issuecomment-2590051276) I received no response so far that's why in case u missed this (#13) I recreated this issue #38

**Comment by muhammad-fiaz** [comment]
i have finally solved this issue by

`pyproject.toml`
```toml

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
logly = ">=0.0.6,<0.1.0"
packaging = ">=24.0,<25.0"
pandas = "^2.2"
numpy = "^1.26"
torch = {version = "^2.5.0", source = "pytorch-gpu"}
torchvision = {version = "^0.20.0", source = "pytorch-gpu"}
torchaudio = {version = "^2.5.0", source = "pytorch-gpu"}
requests = "^2.32"
tqdm = "^4.67"
regex = "^2024.11"
sentencepiece = "^0.2"
tiktoken = "^0.8"
blobfile = "^3.0"
safetensors = "^0.5"
huggingface-hub = "^0.27"
xformers = [
    { platform = "win64", url = "https://download.pytorch.org/whl/cu124/xformers-0.0.29.post1-cp312-cp312-win_amd64.whl"}
]
gradio = "^5.12"
transformers = "^4.48"
datasets = "^3.2"
trl = "^0.13"
peft = "^0.14"
bitsandbytes = "^0.45"
unsloth = { extras = ["cu124onlytorch251", "huggingface"], version = "^2025.1.3" }
unsloth-zoo = " ^2025.1.3"
accelerate = "^1.2.1"
gradio-client = "^1.5.4"
triton = {url = "https://github.com/woct0rdho/triton-windows/releases/download/v3.1.0-windows.post5/triton-3.1.0-cp312-cp312-win_amd64.whl"}

[[tool.poetry.source]]
name = "pytorch-gpu"
url = "https://download.pytorch.org/whl/cu124"
priority = "explicit"

```

I tried all possible ways but none worked with poetry and also with pip (with freshly venv) but I tried this config with poetry this worked for me now I think the error before was due to the poetry's way of `venv` handling and also assume changing the `venv` also causes this but you can clear cache and delete the cache folder recreate the `venv` along with this config solution with poetry
to clear cache
```bash
poetry cache clear --all pypi
```
> use virtual environment 

then use this
```toml
triton = {url = "https://github.com/woct0rdho/triton-windows/releases/download/v3.1.0-windows.post5/triton-3.1.0-cp312-cp312-win_amd64.whl"}
```
instead of 
```toml
# if you use this the poetry does not install the deps correctly and shows `ModuleNotFoundError: No module named 'triton'
triton = {platform="win64",url = "https://github.com/woct0rdho/triton-windows/releases/download/v3.1.0-windows.post5/triton-3.1.0-cp312-cp312-win_amd64.whl"}
# or with 'win32' 
```

I hope this helps :) [duplicate](#13) and [resolved issue with unsloth](https://github.com/unslothai/unsloth/issues/1547)
